version: "3.9"

services:
  db:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db:/var/lib/postgresql
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql

  api:
    build: "./api"
    container_name: node-api-container
    restart: always
    volumes:
      - ./api:/home/node/app
    ports: 
      - "9001:9001"
    depends_on: 
      - db

  front:
    build: "./elearning-platform"
    container_name: angular
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - api
